#define POS_TOP(o)          o->position ((Fl::w() - o->w()) / 2, 1)
#define POS_CENTER(o)       o->position ((Fl::w() - o->w()) / 2, (Fl::h() - o->h()) / 2)
#define POS_BOTTOM(o)       o->position ((Fl::w() - o->w()) / 2,  Fl::h() - o->h())
#define POS_TOP_LEFT(o)     o->position (1, 1)
#define POS_LEFT(o)         o->position (1, (Fl::h() - o->h()) / 2)
#define POS_BOTTOM_LEFT(o)  o->position (1,  Fl::h() - o->h())
#define POS_TOP_RIGHT(o)    o->position (Fl::w() - o->w(), 1)
#define POS_RIGHT(o)        o->position (Fl::w() - o->w(), (Fl::h() - o->h()) / 2)
#define POS_BOTTOM_RIGHT(o) o->position (Fl::w() - o->w(),  Fl::h() - o->h())

#define POS_TOP_(o)          o.position ((Fl::w() - o.w()) / 2, 1)
#define POS_CENTER_(o)       o.position ((Fl::w() - o.w()) / 2, (Fl::h() - o.h()) / 2)
#define POS_BOTTOM_(o)       o.position ((Fl::w() - o.w()) / 2,  Fl::h() - o.h())
#define POS_TOP_LEFT_(o)     o.position (1, 1)
#define POS_LEFT_(o)         o.position (1, (Fl::h() - o.h()) / 2)
#define POS_BOTTOM_LEFT_(o)  o.position (1,  Fl::h() - o.h())
#define POS_TOP_RIGHT_(o)    o.position (Fl::w() - o.w(), 1)
#define POS_RIGHT_(o)        o.position (Fl::w() - o.w(), (Fl::h() - o.h()) / 2)
#define POS_BOTTOM_RIGHT_(o) o.position (Fl::w() - o.w(),  Fl::h() - o.h())

